### ISSUE TITLE
Your title for this repo is Incorrect

### ISSUE THREAD

**Issue by DiscoSteve** [danik4985/cesilc#1]
Your 50 years comment is incorrect.

Please see https://github.com/DiscoSteve/awk-cesil which is where I published an awk version of CESIL in 2012

**Comment by danik4985** [comment]
The comment says

> 47 years later, introducing a brand new, fast, epic cesil **compiler**.

What you have written is an **interpreter**.

A compiler is not an interpreter. I have found multiple cesil interpreters, but no compilers. If you find a cesil **compiler** made in the last 47 years (besides mine), please let me know.
